# -*- coding: utf-8 -*-
"""aula-08.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UiW3oqThSv9LxRW-Cp6oP40iCbilwJqq
"""

# ----------------------------- AULA 07

# **Exercício 1: Contagem regressiva simples**
# Escreva um programa que exiba uma contagem regressiva de 10 a 1, e depois imprima "Fogo!".



# **Exercício 2: Soma de números pares**
# Peça ao usuário que insira um número inteiro positivo e, em seguida, calcule a soma de todos os números pares de 2 até o número inserido.



# **Exercício 3: Tabuada de multiplicação**
# Peça ao usuário para inserir um número inteiro e mostre a tabuada de multiplicação desse número de 1 a 10.



# **Exercício 4: Números ímpares reversos**
# Exiba uma contagem regressiva de números ímpares de 99 a 1.




# Random ----------------------------- AULA 07

# import random

# 1 - Crie um número aleatório de 10, 5

# n1 = random.randint(5,10)
# print(n1)

# 2 - Crie 3 números aleatórios

# n2 = random.random()
# n3 = random.random()
# n4 = random.random()
# print(n2,'\n',n3,'\n',n4)

# 3 - Crie um número aleatório entre 10 a 30 utilize o range()

# n5 = random.randrange(10,30)
# print(n5)



# --------------------------------------- AULA 08 ------------------------------------------------

# my_tuple = (1,3,658,48,78,94)
# my_indice = my_tuple[0]
# print(my_indice)

# my_tuple2 = (10,20,58,55,60,70)
# my_tuple = my_tuple2
# print(my_tuple)

# --------------------------------------- MÉTODO LIST () #Transforma uma tupla em lista

# tuple1 = (1,5,8,78,9,64)
# print(tuple1)

# transform = list(tuple1)
# print(transform)


# vogais = ('a','b','c','d','e')
# for letras in vogais:  #Imprime uma embaixo da outra
#     print(letras)

# --------- -------------- Desempacotar elementos da lista
# regiao = ('Cataratas','Amazônia')
# s,n = regiao   #As variaveis precisam ter a quantidade de indices da tupla
# print('Região sul: ', s)
# print('Região norte: ', n)


# -------------------------------- Exercícios

# **EXERCÍCIOS:**

# 1 - Crie uma tupla chamada `frutas` com pelo menos 5 frutas diferentes. Em seguida, acesse e imprima o terceiro elemento da tupla.

# frutas = ('Maça', 'Laranja', 'Banana','Manga', 'Ameixa')
# print(frutas[2])

# 2 - Crie uma tupla chamada `numeros` com alguns números inteiros. Em seguida, converta essa tupla em uma lista e imprima a lista resultante.

# numeros = (2,87,99,85,47)
# transform1 = list(numeros)
# print(transform1)

# 3 - Crie uma tupla chamada `meses` com os nomes dos meses do ano até Setembro. Use um loop `for` para imprimir cada mês em uma linha separada.

# meses = ('Janeiro','Fevereiro', 'Março','Abril','Maio')
# for i in meses:
#     print(i)

# 4 - Crie uma lista chamada `notas` com algumas notas de alunos. Em seguida, converta essa lista em uma tupla e imprima a tupla resultante.

# notas = [7,8,9,7,5]
# nota_tupla = tuple(notas)
# print(nota_tupla)

# 5 - Crie uma lista chamada `ponto` que represente as coordenadas (x, y) de um ponto. Em seguida, desempacote os elementos da lista em duas
# variáveis separadas (x e y) e imprima os valores.

# ponto = [56,44]
# x,y = ponto
# print(f'Coordenada X: {x}')
# print(f'Coordenada Y: {y}')


#-------------------------------------------------- INTRODUÇÃO A FUNÇÃO def nomevariavel()

#O objetivo da minha função é somar

#Oque é uma Função ? É ação no meu código (Bloco de código)

# def soma():
#     a = 15
#     b = 10
#     print('O número é: 'a + b)


# def subtracao():
#     c1 = int(input('Digite um número: '))
#     d1 = int(input('Digite outro número: '))
#     print(c1 - d1)


# def saudacao():
#     nome = input('Digite seu nome: ')
#     idade = input('Digite sua idade: ')
#     print(f'Olá {nome}, boa tarde! Sua idade é {idade}')

# soma()
# subtracao()
# saudacao()

#------------------------------------ Calculadora

def calculadora():
    a3 = int(input('N1= '))
    b3 = int(input('N2= '))

    somaN = int(a3+b3)
    subN = int(a3-b3)
    MultiN = int(a3*b3)
    DivideN = int(a3/b3)

    print(f'A soma desses números é -> {somaN}')
    print(f'A subtração desses números é -> {subN}')
    print(f'A multiplicação desses números é -> {MultiN}')
    print(f'A divisão desses números é -> {DivideN}')

calculadora()

print("SOMA, SUBTRAÇÃO, MULTIPLICAÇÃO, DIVISÃO")

operacao = input('Digite uma operação do texto acima: ')

n1 = int(input('N1: '))
n2 = int(input('N2: '))

def soma():
    print('Resultado: ', n1+n2)
def subtracao():
    print('Resultado: ', n1-n2)
def multiplicacao():
    print('Resultado: ', n1*n2)
def divisao():
    print('Resultado: ', n1/n2)

if operacao == 'soma':
    soma()
elif operacao == 'subtracao':
    subtracao()
elif operacao == 'multiplicação':
    multiplicacao()
elif operacao == 'divisão':
    divisao()